# This workflow automates the CI/CD process for your frontend application.
# It builds a Docker image and pushes it to the GitHub Container Registry (ghcr.io).
# It does not manage Kubernetes manifests, which live in a separate GitOps repository.

name: Frontend CI/CD

# The workflow will run on every push to the 'main' branch.
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the frontend repository.
      - name: Checkout frontend repo
        uses: actions/checkout@v4

      # Step 2: Log in to the GitHub Container Registry (ghcr.io).
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.PAT_USER }}
          password: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      # Step 3: Build and push the Docker image.
      # We use the short commit SHA as a unique tag for the Docker image.
      - name: Build and push frontend Docker image
        run: |
          IMAGE_TAG=${{ github.sha }}
          docker build -t ghcr.io/diardzairdev/bellat-frontend:$IMAGE_TAG .
          docker push ghcr.io/diardzairdev/bellat-frontend:$IMAGE_TAG
          
      # --- GitOps Steps Start Here ---

      # Step 4: Checkout the GitOps repository where your manifests live.
      - name: Checkout GitOps repo
        uses: actions/checkout@v4
        with:
          # Use a Personal Access Token (PAT) with read/write permissions
          # to the GitOps repository. This is required for the push step.
          repository: diardzairdev/k8s-gitops
          path: k8s-gitops
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      # Step 5: Update the image tag in the frontend manifest.
      - name: Update image tag in manifest
        run: |
          NEW_IMAGE_TAG="ghcr.io/diardzairdev/bellat-frontend:${{ github.sha }}"
          
          # Use sed to replace the old image tag with the new one.
          sed -i "s|ghcr.io/diardzairdev/bellat-frontend:.*|$NEW_IMAGE_TAG|g" k8s-gitops/clusters/my-cluster/frontend-deployment.yaml
          
          echo "Updated frontend-deployment.yaml:"
          cat k8s-gitops/clusters/my-cluster/frontend-deployment.yaml

      # Step 6: Commit the changes and push to the GitOps repository.
      # We use a dedicated action for this for reliability.
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "feat(ci): Update frontend image tag to ${{ github.sha }}"
          repository: k8s-gitops
